// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGunHnhNRPLctkbCZPS_fq5hvw5IHl0ug',
    appId: '1:149983993155:web:450fd2f40d4544a45b23f6',
    messagingSenderId: '149983993155',
    projectId: 'ducklist-app',
    authDomain: 'ducklist-app.firebaseapp.com',
    storageBucket: 'ducklist-app.firebasestorage.app',
    measurementId: 'G-219C8YFS4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyQMMZyF8Nc3hKP96cY-9fSk_L6eIMV8Q',
    appId: '1:149983993155:android:614178d815324a815b23f6',
    messagingSenderId: '149983993155',
    projectId: 'ducklist-app',
    storageBucket: 'ducklist-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd-4K28qVJJDHvL6BMZoAdRS5z3-0PpLM',
    appId: '1:149983993155:ios:a403244fe14e52465b23f6',
    messagingSenderId: '149983993155',
    projectId: 'ducklist-app',
    storageBucket: 'ducklist-app.firebasestorage.app',
    iosBundleId: 'com.example.ducklist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd-4K28qVJJDHvL6BMZoAdRS5z3-0PpLM',
    appId: '1:149983993155:ios:a403244fe14e52465b23f6',
    messagingSenderId: '149983993155',
    projectId: 'ducklist-app',
    storageBucket: 'ducklist-app.firebasestorage.app',
    iosBundleId: 'com.example.ducklist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGunHnhNRPLctkbCZPS_fq5hvw5IHl0ug',
    appId: '1:149983993155:web:8fd38d57d237f27b5b23f6',
    messagingSenderId: '149983993155',
    projectId: 'ducklist-app',
    authDomain: 'ducklist-app.firebaseapp.com',
    storageBucket: 'ducklist-app.firebasestorage.app',
    measurementId: 'G-VYK55SLSFB',
  );
}
